# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shudman
email: contact@shudman.com
description: > # this means to ignore newlines until "baseurl:"
  This is how I kill time sometimes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.shudman.com/"
twitter_username: seedform
github_username:  seedform

# Build settings
markdown: kramdown

host: 0.0.0.0
